services:
  web:
    container_name: web
    build:
      dockerfile: docker/web/Dockerfile
      target: ${APP_ENV}
    restart: always
    ports:
      - ${WEB_PORT}:80
      - ${WEB_PORT_SSL}:443
    env_file:
      - .env
    volumes:
      - ./src:/var/www/src
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf