services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      target: ${APP_ENV}
    restart: always
    ports:
      - ${WEB_PORT}:80
    env_file:
      - .env
    volumes:
      - ./public:/usr/share/nginx/html